# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    # Run the steps with Docker
    docker:
      - image: cimg/python:3.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/vlapy

    steps:
      - checkout

      # Load pip cache
#      - restore_cache:
#          keys:
#            - pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}
#            - pip-packages-v1-{{ .Branch }}
#            - pip-packages-v1

      # Setup Python venv
      - run:
          name: setup python virtual env
          command: python3 -m venv venv

      - run:
          name: install python packages
          command: |
            . venv/bin/activate
            pip3 install -U pip
            pip3 install . --progress-bar off
            pip3 install black
            pip3 install pytest pytest-cov codecov

      # save pip cache
#      - save_cache:
#          paths:
#            - venv
#          key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}

      # Run python linting checks
      - run:
          name: run python linting checks
          command: |
            . venv/bin/activate
            black --check vlapy

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov-report=xml --cov=vlapy

      # upload code coverage report
      - run:
          name: upload code coverage report
          command: |
            . venv/bin/activate
            codecov

      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      - store_test_results:
          path: test-results

      # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: test-results
          destination: tr1
